steps:
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        npm run build
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', 'dist/*', 'gs://nexus_bucket1']

options:
  logging: CLOUD_LOGGING_ONLY
